steps:

# ----------------------------------------------------
# Step 0 — Create the local cache directory
# ----------------------------------------------------
- name: "gcr.io/cloud-builders/gcloud" # Use the working builder image
  entrypoint: "bash"                   # <--- FIX 1: Set the entrypoint to 'bash'
  args:
    - "-c"
    - "mkdir -p /workspace/pip-cache"  # <--- FIX 2: Run mkdir inside the shell

    
# ----------------------------------------------------
# Step 1 — Restore pip cache from GCS (Now this step will work)
# ----------------------------------------------------
- name: gcr.io/cloud-builders/gsutil
  args:
    [
      "rsync", "-r",
      "gs://bucket-pip-cache/pip/",
      "/workspace/pip-cache/"
    ]

# ----------------------------------------------------
# Step 2 — install & run
# ----------------------------------------------------
- name: "python:3.11"
  entrypoint: "bash"
  args:
    - "-c"
    - |
        pip install --cache-dir /workspace/pip-cache -r requirements.txt
        python3 run.py

# ----------------------------------------------------
# Step 3 — post_build
# ----------------------------------------------------
- name: "gcr.io/cloud-builders/gcloud" # <--- FIXED from 'bash'
  entrypoint: "bash"
  args:
    - "-c"
    - |
        ls

# ----------------------------------------------------
# Step 4 — Store updated cache back to GCS
# ----------------------------------------------------
- name: gcr.io/cloud-builders/gsutil
  args:
    [
      "rsync", "-r",
      "/workspace/pip-cache/",
      "gs://bucket-pip-cache/pip/"
    ]

# ----------------------------------------------------
# Step 5 — Upload Primary Artifacts (Preserves directory structure)
# ----------------------------------------------------
- name: gcr.io/cloud-builders/gsutil
  args:
    [
      "cp", "-R",
      "frame_data/",
      "frame_data/frames",
      "frame_data/predict",
      "gs://demo-artifact-bucket/frame_data"
    ]

# ----------------------------------------------------
# Step 6 — Upload Secondary Artifact (result.json)
# ----------------------------------------------------
- name: gcr.io/cloud-builders/gsutil
  args:
    [
      "cp",
      "result.json",
      "gs://demo-artifact-bucket/videoFrames/"
    ]



