steps:
# ----------------------------------------------------
# Step 0 — Restore pip cache from GCS
# ----------------------------------------------------
- name: gcr.io/cloud-builders/gsutil
  args:
    [
      "rsync", "-r",
      "gs://bucket-pip-cache/pip/",
      "/workspace/pip-cache/"
    ]

# ----------------------------------------------------
# Step 1 — install & run
# ----------------------------------------------------
- name: "python:3.11"
  entrypoint: "bash"
  args:
    - "-c"
    - |
        pip install --cache-dir /workspace/pip-cache -r requirements.txt
        python3 run.py

# ----------------------------------------------------
# Step 2 — post_build
# ----------------------------------------------------
- name: "gcr.io/cloud-builders/gcloud" # <--- FIXED from 'bash'
  entrypoint: "bash"
  args:
    - "-c"
    - |
        ls

# ----------------------------------------------------
# Step 3 — Store updated cache back to GCS
# ----------------------------------------------------
- name: gcr.io/cloud-builders/gsutil
  args:
    [
      "rsync", "-r",
      "/workspace/pip-cache/",
      "gs://bucket-pip-cache/pip/"
    ]

# ----------------------------------------------------
# New Step 4 — Upload Primary Artifacts (Preserves directory structure)
# ----------------------------------------------------
- name: gcr.io/cloud-builders/gsutil
  args:
    [
      "cp", "-R",
      "frame_data/frames",
      "frame_data/predict",
      "gs://demo-artifact-bucket/main-artifacts/frame_data"
    ]

# ----------------------------------------------------
# New Step 5 — Upload Secondary Artifact (result.json)
# ----------------------------------------------------
- name: gcr.io/cloud-builders/gsutil
  args:
    [
      "cp",
      "result.json",
      "gs://demo-artifact-bucket/videoFrames/"
    ]



